// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcrwTiYeOTQClPUyAD4NtxaITM5uILi_U',
    appId: '1:932574768473:web:98a66b7723ef3ed479b048',
    messagingSenderId: '932574768473',
    projectId: 'messerp-26027',
    authDomain: 'messerp-26027.firebaseapp.com',
    storageBucket: 'messerp-26027.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4G3aS7ylfG764KhaXKifHA_cCK24xbxQ',
    appId: '1:932574768473:android:7e26adae471cfa1e79b048',
    messagingSenderId: '932574768473',
    projectId: 'messerp-26027',
    storageBucket: 'messerp-26027.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgA_UtRTLnd8Ut1VdERrU7ZxdZuEE9jZo',
    appId: '1:932574768473:ios:b1dd4e76e19ecb1779b048',
    messagingSenderId: '932574768473',
    projectId: 'messerp-26027',
    storageBucket: 'messerp-26027.appspot.com',
    iosBundleId: 'com.example.messErp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgA_UtRTLnd8Ut1VdERrU7ZxdZuEE9jZo',
    appId: '1:932574768473:ios:a751f641ba7496ce79b048',
    messagingSenderId: '932574768473',
    projectId: 'messerp-26027',
    storageBucket: 'messerp-26027.appspot.com',
    iosBundleId: 'com.example.messErp.RunnerTests',
  );
}
